### ISSUE TITLE
Can we go back to released version of robot web tools

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env-targets#342]

**Comment by MatthijsBurgh** [comment]
Earlier discussion: https://github.com/tue-robotics/tue-env/issues/200

**Comment by ar13pit** [comment]
Based on this discussion, I say yes. If you can test and verify everything works, then I see no reason to be building this from source.

**Comment by MatthijsBurgh** [comment]
Fixed by #343
