### ISSUE TITLE
Missing repo's for target hero2

### ISSUE THREAD

**Issue by PetervDooren** [tue-robotics/tue-env-targets#35]
Currently two github repo's are not installed on hero2. These are [telegram_ros](https://github.com/tue-robotics/telegram_ros) and [conversation_engine](https://github.com/tue-robotics/conversation_engine).

Solution: Either the repos are added to the hero2 target (or another relevant target), or a dependency on the repo's should be added in a package.xml.

**Comment by PetervDooren** [comment]
@LoyVanBeek and @MatthijsBurgh, where should these dependencies/install targets be fixed?

Telegram_ros is only required on the robot itself so we could add that repo to the hero2 target

The conversation_engine is needed for certain challenges like the gpsr so we could add a dependency to the challenge_gpsr package.xml. However I don't know how this is normally done.

**Comment by MatthijsBurgh** [comment]
Currently the dependency on the `action_server` is in `tue-middleware` target. But I think, this should **also** be in the challenges that use the `action_server`. I think this should be the same for the `converstation_engine` as they are in the 'same corner' of our system.
